general:
  correct_pvals: true
  elements: null
  handle_na: ignore
  model: linear
  multi: true
  output_dir: ./
  predictor_random_effect: null
  predictors: null
  predictors_file: null
  predictors_intercept_0: null
  predictors_multi_force: null
  sample_column: null
  samples: null
  significance_threshold: 0.2
metrics:
  metric_1:
    adjust: false
    elements_total_by: included
    file: all_mutdensities.tsv
    metric_name: mutdensity
    muttype:
    - snv
    - snv_indel
    region:
    - protein_affecting
    - non_protein_affecting
    samples_total_by: included
plot:
  predictors_colors: null
  predictors_names: null
