name: Nextflow Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run Nextflow lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v2.0.0
        with:
          version: latest-stable
          all: false

      - name: Run Nextflow lint
        run: nextflow lint -format -harshil-alignment *
